swagger: "2.0"
info:
  version: "1.0.0"
  title: "E-Commerce API"
  description: "API for managing brands, products, and user cart"

host: "localhost:3000"
schemes:
  - "http"

basePath: "/api"

produces:
  - "application/json"

paths:
  /brands:
    get:
      summary: Brands
      description: >
        The brands endpoint returns all brands of sunglasses.
        The response will include the id and name of each sunglass brand.
      tags:
        - brands
      responses:
        200:
          description: An array of brands
          schema:
            type: array
            items:
              type: object
              required:
                - id
                - name
              properties:
                id:
                  type: string
                name:
                  type: string

  /brands/{id}/products:
    get:
      summary: Products
      description: >
        The products by brand id endpoint returns all products
        that match the brand id parameter.
      tags:
        - products
      parameters:
        - name: id
          in: path
          description: The id of the brand to accept
          required: true
          type: string
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              type: object
              required:
                - id
                - categoryId
                - name
                - price
                - imageUrls
              properties:
                id:
                  type: string
                categoryId:
                  type: string
                name:
                  type: string
                description:
                  type: string
                price:
                  type: string
                imageUrls:
                  type: array
                  items:
                    type: string
        404:
          description: No products with matching brand id exist.
  /products:
    get:
      responses:
        200:
          description: An array of products.
          schema:
            type: array
            items:
              type: object
              required:
                - id
                - categoryId
                - name
                - price
                - imageUrls
              properties:
                id:
                  type: string
                categoryId:
                  type: string
                name:
                  type: string
                description:
                  type: string
                price:
                  type: string
                imageUrls:
                  type: array
                  items:
                    type: string
        404:
          description: No products available.
  /login:
    post:
      summary: login
      description: >
        The login endpoint checks if user credentials exist in the user database and generates a jwt web token.
      tags:
        - login
      parameters:
        - name: username
          in: query
          description: The username
          required: true
          type: string
        - name: password
          in: query
          description: user password
          required: true
          type: string
      response:
        200:
          description: >
            If a user credential is verified, a jwt web token is returned to the client.
          schema:
            type: object
            properties:
              token:
                type: string
        401:
          description: >
            If the user credentials cannot be verified, return a 401 error.
  /me/cart:
    get:
      summary: cart
      description: >
        The me/cart endpoint returns the user's cart.
      tags:
        - cart
      headers:
        - name: Authorization
          in: headers
          description: bearer token
          required: true
          type: string
      response:
        200:
          description: >
            If a jwt token is valid, return the user's cart.
          schema:
            type: array
            items:
              type: object
              required:
                - id
                - brand
                - productName
                - quantity
              properties:
                id:
                  type: string
                brand:
                  type: string
                productName:
                  type: string
                quantity:
                  type: integer
        401:
          description: >
            If no jwt token was found in the headers, return 401.
    post:
      summary: cart
      tags:
        - cart
      headers:
        - name: Authorization
          in: headers
          description: bearer token
          required: true
          type: string
      parameters:
        - name: id
          in: path
          description: The id of the product being added to the cart.
          required: true
          type: string
      responses:
        200:
          description: >
            If a jwt token is valid, add a item to the user's cart.
          schema:
            type: array
            items:
              type: object
              required:
                - id
                - brandName
                - description
                - quantity
              properties:
                id:
                  type: string
                brandName:
                  type: string
                description:
                  type: string
                quantity:
                  type: integer
