swagger: "2.0"
info:
  version: "1.0.0"
  title: "E-Commerce API"
  description: "API for managing brands, products, and user cart"
host: "localhost:3000"
schemes:
  - "http"
basePath: "/api"
produces:
  - "application/json"
paths:
  /api/brands:
    get:
      summary: Brands
      description: |
        The brands endpoint returns all brands of sunglasses. The response will include the id and name of each sunglass brand.
      tags:
        - brands
      responses:
        200:
          description: An array of brands
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
              required:
                - id
                - name
